version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: pg_database
    environment:
      POSTGRES_DB: test_tap
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pg-data:
